### ISSUE TITLE
Dosya yolu sorunu

### ISSUE THREAD

**Issue by emrahkirdok** [Sahinozturkk/Genome-Analyse-Nf#1]
Betikte bulunan girdi ve çıktı dosya yollarını anonimleştirelim:

```
params.fastq="data/*.fastq.gz"
params.qc_report="results/fastqc-before-process"
```

Ayrıca girdi dosyaları her zaman `data` içinde, çıktılar ise her zaman `results` içinde olsun.

**Comment by Sahinozturkk** [comment]
Dosya yolları düzeltildi.
Dosya klasörleri düzeltildi.
Publish Dir(...) kodu açıklandı.
Data için "Drive" bağlantısı eklendi.
Repositorie tek parça olarak düzenlendi.
